location: "eastus2"
rg_name: "IOT_DevOps_EDGE_EU_RG"
subscription_id: "bab63f26-ad0e-444d-a3e8-4bdb97cbea58"
user_name: "2f88ddc3-134c-4149-89d0-04ae4176ae22"
password: "O=vl=_pn4nLxo/Mo8h2OpTcUWqFwZ11s"
tenant: "415a8c7e-8647-4b46-b291-9cd6c3cde41d"
simulator_id: "simulator_138459"
sensor_id: "sensor_428098"
iotHubName: "iotdevopsdemohub"
simulator_connection_string: "HostName=iotdevopsdemohub.azure-devices.net;DeviceId=simulator_138459;SharedAccessKey=UKd200WIHAZ7D6UVfbI9BF/XgqjMnylHEMbF0t0aXhs="
sensor_connection_string: "HostName=iotdevopsdemohub.azure-devices.net;DeviceId=sensor_428098;SharedAccessKey=32fIXxOBhVTbo3W2qsxAC1bv+Xd6U+1vqbQhHTezesc="
baud_rate: 9600