location: "eastus2"
rg_name: ""
subscription_id: ""
user_name: ""
password: ""
tenant: ""
simulator_id: "simulator_138459"
sensor_id: "sensor_428098"
iotHubName: "iotdevopsdemohub"
simulator_connection_string: ""
sensor_connection_string: ""
baud_rate: 9600
